apiVersion: v1
kind: Pod
metadata:
  name: busybox-log
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ["sh", "-c"]
      args:
        - |
          i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done
