apiVersion: v1
kind: Pod
metadata:
  name: nginx-liveness-ls
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /
          port: 80