---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-with-vol
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ["sleep"]
      args: ["3600"]
      volumeMounts:
        - name: empty
          mountPath: /etc/foo
  volumes:
    - name: empty
      persistentVolumeClaim:
        claimName: mypvc
