---
apiVersion: v1
kind: Pod
metadata:
  name: dual-busybox
spec:
  containers:
    - name: alpha
      image: busybox:latest
      command: ["sleep"]
      args: ["3600"]
      volumeMounts:
        - name: empty
          mountPath: /etc/foo
    - name: bravo
      image: busybox:latest
      command: ["sleep"]
      args: ["3600"]
      volumeMounts:
        - name: empty
          mountPath: /etc/foo
  volumes:
    - name: empty
      emptyDir: {}
