---
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    app: v1
  annotations:
    description: my description
spec:
  containers:
    - name: nginx
      image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app: v2
  annotations:
    description: my description
spec:
  containers:
    - name: nginx
      image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx3
  labels:
    app: v1
  annotations:
    description: my description
spec:
  containers:
    - name: nginx
      image: nginx:latest
