apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  securityContext:
    runAsUser: 101
  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "SYS_TIME"]