apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: mysecret2
          mountPath: /etc/foo
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret2
              key: username
  volumes:
    - name: mysecret2
      secret:
        secretName: mysecret2
