---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myuser
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  serviceAccountName: myuser
  containers:
    - name: nginx
      image: nginx
