---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  initContainers:
    - name: init-busybox
      image: busybox:latest
      command: ["wget"]
      args: ["-O", "/work-dir/index.html", "http://neverssl.com/online"]
      volumeMounts:
        - name: share
          mountPath: /work-dir
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: share
          mountPath: /usr/share/nginx/html
    - name: busybox
      image: busybox:latest
      command: ["tail"]
      args: ["-f", "/dev/null"]
  volumes:
    - name: share
      emptyDir: {}
